# Generated by Django 4.2.2 on 2023-07-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chekigari', '0002_alter_users_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=250)),
            ],
        ),
    ]
