# Generated by Django 4.2.2 on 2023-07-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chekigari', '0003_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploaded_files/')),
            ],
        ),
    ]
