# Generated by Django 4.2.2 on 2023-08-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chekigari', '0004_uploadfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('cc', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=10)),
                ('transmission', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('available_units', models.IntegerField()),
                ('photo', models.ImageField(upload_to='shopvehicles/')),
                ('other_photos', models.ImageField(blank=True, null=True, upload_to='shopvehicles/')),
            ],
        ),
    ]
