# Generated by Django 4.2.2 on 2023-08-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chekigari', '0005_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='other_photos',
        ),
        migrations.AddField(
            model_name='shop',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='shop',
            name='timeStamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='shopvehicles/'),
        ),
    ]
