# Generated by Django 4.2.2 on 2023-08-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chekigari', '0006_remove_shop_other_photos_shop_price_shop_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
