# Generated by Django 4.2.2 on 2023-08-05 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chekigari', '0008_alter_shop_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='price',
        ),
    ]
